baseurl = "https://blog.kihh.xyz"
languageCode = "zh-Hans"
paginate = 5
title = "Kihh的博客"

DefaultContentLanguage = "zh-cn"

hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "Kihh123"